---
title: Missouri Tile
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
email: sales@missouritile.biz
description: Missouri Tile is a family owned and operated tile store and showroom
  with a large selection of tiles that will accommodate any budget.
url: http://missouritile.biz
banner: millstone b.png
markdown: kramdown
gems:
- jekyll-sitemap
menu:
  main:
  - title: Welcome
    permalink: "/"
  - title: Showroom
    permalink: "/showroom"
  - title: Video
    permalink: "/video"
  - title: Products
    permalink: "/products"
  - title: Galleries
    permalink: "/galleries"
    submenu: galleries
  - title: Contact
    permalink: "/contact"
  galleries:
  - title: Kitchens
    permalink: "/galleries/kitchens"
  - title: Bathrooms
    permalink: "/galleries/bathrooms"
  - title: Outdoors
    permalink: "/galleries/outdoors"
  - title: Commercial
    permalink: "/galleries/commercial"
  - title: Backsplash
    permalink: "/galleries/backsplash"
  - title: Wetbar
    permalink: "/galleries/wetbar"
  - title: Fireplace
    permalink: "/galleries/fireplace"
